const ENTRY_FACADE_TYPE_ATTRIBUTE = "BC_ENTRY_FACADE_TYPE";
const ENTRY_PROPERTY_OTP = "BC_ENTRY_TOTP_PROPERTY";

module.exports = {
    ENTRY_FACADE_TYPE_ATTRIBUTE,
    ENTRY_PROPERTY_OTP,
    ENTRY_TYPE_CREDITCARD: "credit_card",
    ENTRY_TYPE_LOGIN: "login",
    ENTRY_TYPE_NOTE: "note",
    ENTRY_TYPE_SSHKEY: "ssh_key",
    ENTRY_TYPE_WEBSITE: "website"
};
